version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_db
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: rabbitmq_test
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_DEFAULT_VHOST=/
volumes:
  databases:
